-- GROUP BY 절에 쓸 수 있는 그룹핑함수
-- 1. ROLLUP(col_a, col_b)
--      : col_a로 그룹바이해서 통계, col_a + col_b를 합쳐서 그룹바이 통겨, 전체 통계
-- 2. CUBE(col_a, col_b)
--      : col_a 그룹바이 통계, col_b 그룹바이 통계, col_a + col_b 그룹바이 통겨, 전체 통계
-- 3. GROUPING SETS (col_a, col_b)
--      : col_a 통계, col_b 통계
-- * SELECT절에 쓰느 GROUPING 함수
--      : 함수의 인자값이 null이면 1리턴, 아니면 0리턴
--      ex) GROUPING(manager_id) => manager_id가 null이면 1리턴
 